// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Panchos atack":
            case "5@H},@~dr|5;l0:QhEmJ":return [img`
....................
.....eeeeee..1......
....eeeeeeee1.......
...eeeeeeeeee.......
..eeeeeeeeeeee......
..eeeeeeeeeeee......
..eeeeeeeeeeee......
.eeeebfeefbeeee.....
.eeee1feef1eeee.....
..feeee22eeeef......
...feee21eeef.......
..eefeeeeeefee......
.dedfeeeeeefde......
.deefeeeeeefee......
.ddddffffff.........
.....ff..ff.........
`, img`
....................
.....eeeeee..1......
....eeeeeeee1.......
...eeeeeeeeee.......
..eeeeeeeeeeee......
..eeeeeeeeeeee......
..eeeeeeeeeeee......
.eeeebfeefbeeee.....
.eeee1feef1eeee.....
..feeee22eeeef......
...feee21eeef.ee....
..eefeeeeeefeede....
.dedfeeeeeefeee.....
.deefeeeeeefe.......
.ddddffffff.........
.....ff..ff.........
`, img`
....................
.....eeeeee..1......
....eeeeeeee1.......
...eeeeeeeeee.......
..eeeeeeeeeeee......
..eeeeeeeeeeee......
..eeeeeeeeeeee......
.eeeebfeefbeeee.....
.eeee1feef1eeee.....
..feeee22eeeef.ee...
...feee21eeef.ede...
..eefeeeeeefeeee....
.dedfeeeeeefeeee....
.deefeeeeeefe.......
.ddddffffff.........
.....ff..ff.........
`, img`
....................
.....eeeeee..1......
....eeeeeeee1.......
...eeeeeeeeee.......
..eeeeeeeeeeee......
..eeeeeeeeeeee......
..eeeeeeeeeeee......
.eeeebfeefbeeee.....
.eeee1feef1eeee.ee..
..feeee22eeeef.ede..
...feee21eeef.eeee..
..eefeeeeeefeeeee...
.dedfeeeeeefeeee....
.deefeeeeeefe.......
.ddddffffff.........
.....ff..ff.........
`, img`
....................
.....eeeeee..1......
....eeeeeeee1.......
...eeeeeeeeee.......
..eeeeeeeeeeee......
..eeeeeeeeeeee......
..eeeeeeeeeeee......
.eeeebfeefbeeee..ee.
.eeee1feef1eeee.ede.
..feeee22eeeef.eeee.
...feee21eeef.eeee..
..eefeeeeeefeeeee...
.dedfeeeeeefeeee....
.deefeeeeeefe.......
.ddddffffff.........
.....ff..ff.........
`, img`
....................
.....eeeeee..1......
....eeeeeeee1.......
...eeeeeeeeee.......
..eeeeeeeeeeee......
..eeeeeeeeeeee.eee..
..eeeeeeeeeeee.edee.
.eeeebfeefbeeee.eee.
.eeee1feef1eeee.eee.
..feeee22eeeef.eeee.
...feee21eeef.eeee..
..eefeeeeeefeeeee...
.dedfeeeeeefeeee....
.deefeeeeeefe.......
.ddddffffff.........
.....ff..ff.........
`, img`
....................
.....eeeeee.e1e.....
....eeeeeeee1ee.....
...eeeeeeeeeeeee....
..eeeeeeeeeee.eee...
..eeeeeeeeeeee.eee..
..eeeeeeeeeeee.eeee.
.eeeebfeefbeeee.eee.
.eeee1feef1eeee.eee.
..feeee22eeeef.eeee.
...feee21eeef.eeee..
..eefeeeeeefeeeee...
.dedfeeeeeefeeee....
.deefeeeeeefe.......
.ddddffffff.........
.....ff..ff.........
`, img`
....................
.....eeeeee.........
....eeeeeeee........
...eeeeeeeeee.......
..eeeeeeeeeeee..1...
..eeeeeeeeeeee.1ee..
..eeeeeeeeeeee1edee.
.eeeebfeefbeeee.eee.
.eeee1feef1eeee.eee.
..feeee22eeeef.eeee.
...feee21eeef.eeee..
..eefeeeeeefeeeee...
..edfeeeeeefeeee....
..eefeeeeeefe.......
...ddffffff.........
.....ff..ff.........
`, img`
...........d9d......
.....eeeeeed99......
....eeeeeeeed99.....
...eeeeeeeeeed99....
..eeeeeeeeeeeed99...
..eeeeeeeeeeee.d99..
..eeeeeeeeeeee..d1..
.eeeebfeefbeeee..e1.
.eeee1feef1eeee.ede1
..feeee22eeeef.eeee.
...feee21eeef.eeee..
..eefeeeeeefeeeee...
..edfeeeeeefeeee....
..eefeeeeeefe.......
.....ffffff.........
.....ff..ff.........
`, img`
...............d9d..
.....eeeeee...1dd9..
....eeeeeeee.1119d..
...eeeeeeeeee11dd9..
..eeeeeeeeeeee119d..
..eeeeeeeeeeee1dd9..
..eeeeeeeeeeee119d..
.eeeebfeefbeeeedd9..
.eeee1feef1eeee.d...
..feeee22eeeef.e1...
...feee21eeef.ed1...
..eefeeeeeefeeee1...
..edfeeeeeefeeee....
..eefeeeeeefe.......
.....ffffff.........
.....ff..ff.........
`, img`
....................
.....eeeeee.........
....eeeeeeee........
...eeeeeeeeee.......
..eeeeeeeeeeee......
..eeeeeeeeeeee11111.
..eeeeeeeeeeee1111d9
.eeeebfeefbeeee11dd9
.eeee1feef1eeee1dd99
..feeee22eeeef1dd99.
...feee21eeef.dd99..
..eefeeeeeefee199...
..edfeeeeeefd1......
..eefeeeeeef1e......
.....ffffffd........
.....ff..ff.........
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
